services:
  data_pipeline:
    container_name: data_pipeline
    image: python:3.12.1-slim
    working_dir: /app
    environment:
      PATH: "/app/.venv/bin:$PATH"
    
    #keep the container running - for testing
    #command: tail -f /dev/null
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y unixodbc unixodbc-dev &&
      pip install uv &&
      uv sync --locked &&
      uv run python app.py

    volumes:
      #create a volume to export files as output and logs
      - ./output:/app/output

    networks:
      - data_net
    depends_on:
      - sqlserver
      - postgres
    environment:
      SQL_SERVER_HOST: sqlserver
      SQL_SERVER_USER: sa
      SQL_SERVER_PASSWORD: ${SA_PASSWORD}
      SQL_SERVER_DB: WideWorldImporters
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_warehouse
networks:
  data_net:



