
services:
  #define first container to run SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      # password as an enviroment parameter
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
      #defining volumes to access data outside of the container
    volumes:
      - sqlserver_data:/var/opt/mssql 
      #create a network to link containers
    networks:
      - data_net
  # warehouse database
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_warehouse
    volumes:
      - postgres_warehouse:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - data_net
  #python docker for data ingestion
  python_elt:
    container_name: python_elt
    build:
      context: ./python_elt
      dockerfile: ./Dockerfile
    #keep the container running - for testing
    command: tail -f /dev/null

    volumes:
      #create a volume to export files as output and logs
      - ./test_output:/app/output

    networks:
      - data_net
    depends_on:
      - sqlserver
      - postgres
    environment:
      SQL_SERVER_HOST: sqlserver
      SQL_SERVER_USER: sa
      SQL_SERVER_PASSWORD: ${SA_PASSWORD}
      SQL_SERVER_DB: WideWorldImporters
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_warehouse
 
volumes:
  sqlserver_data:
    external: true
    name: sql_server_ERP
  postgres_warehouse:
    external: true
    name: postgres_warehouse
 
networks:
  data_net: